#!/bin/bash

# improvements
## for every argument
## name -> path%name%time

DEBUG=0

while getopts ":d" opt
do
    case ${opt} in
        d ) DEBUG=1 && shift $(OPTIND -1) ;;
        \? ) echo "Argument not understood, terminating" && exit 0;;
    esac
done

for VAR in "$@"
do
    PATHNAME=$(tr "/" "%" <<< $(realpath "$VAR")) 
    DATE=$(date +%m-%d-%y.%H:%M:%S)
    BACKUPNAME="$DATE-$PATHNAME"
    (( $DEBUG )) && echo $BACKUPNAME
    cp "$VAR" "$BACKUPNAME"
    chmod -x "$BACKUPNAME"
    mv "$BACKUPNAME" ~/Backup/.
done

