#!/bin/bash
##############################################################################################
#
# Original author:      Thomas Alexgaard Jensen (https://github.com/thom9258)
#
# License:              MIT
#
# Acknowledgements:     
# 
#
##############################################################################################
# How to use:
#
# OPTS:
# -h            HELP, prints out options
# -n            NO DELETION of output files (log|out|aux)
# 
##############################################################################################

# Global variables
DONTDELETEOUTPUT=0

# Functions
function help() {
echo ""
}

function createpdf {
    BASENAME=$(basename $1 .tex)
    pdflatex "$1"
    (( ! $DONTDELETEOUTPUT )) && [[ -f "$BASENAME.log" ]] && rm -f "$BASENAME.log"
    (( ! $DONTDELETEOUTPUT )) && [[ -f "$BASENAME.out" ]] && rm -f "$BASENAME.out"
    (( ! $DONTDELETEOUTPUT )) && [[ -f "$BASENAME.aux" ]] && rm -f "$BASENAME.aux"
}
# Check for inputs
((!$#)) && echo "no arguments supplied supply argument -h for help" && return || \



# Manage opts
while getopts "hd" opt
do
    case ${opt} in
        h  ) help && shift $((OPTIND-1))  ;;
        d  ) DONTDELETEOUTPUT=1 && shift $((OPTIND-1)) ;;
        \? ) echo "Argument not understood, write -h for help." && exit 1 ;;
    esac
done

# manage input files
for VAR in "$@"
do
    case $VAR in
        *.tex ) createpdf "$VAR" ;;
    esac
done
exit 0
