#!/bin/bash
((!$#)) && echo "no arguments supplied supply argument -h for help" && return || \

while getopts "z" opt; do
    case ${opt} in
        z ) zathura $1 && echo "executed in zathura mode";;
    esac
done

case $1 in
    *.pdf ) okular $1 && ls;;
    *.tex ) pdflatex $1 && ls;;
    *.md ) pandoc $1 -f markdown-implicit_figures -t latex -s -o $2;;
    -h ) echo "this is a all-in-one command to convert text files to pdf or to just open pdf files using okular.
Current inputs consist of *.tex | *.pdf filetypes.
-h    Show this message";;
#    *.tex ) pdflatex $1 && rm *.aux && rm -i *.log && ls -Al && exit 0;;
#    * ) echo "ERROR! Input valid file" ;;
esac
