#!/bin/bash

((!$#)) && echo "Please provide an argument file/directory" && return || \
for var in "$@"
do
    cp -r "$var" ~/Trash/"$var" && rm -r $var  || echo "could not move '$var' to ~/Trash/"
done
