#!/bin/bash

STD_OPTIONS="--no-fehbg --bg-fill"
STD_PATH="$HOME/.wallpaper"
VIEW_WALLPAPER=0

while getopts "hvr" opt
do
    case ${opt} in
        h ) echo "v to view and set, r to reload to last wallpaper" ; exit 0 ;;
        v ) VIEW_WALLPAPER=1 && shift $((OPTIND-1)) ;;
        r ) feh $STD_OPTIONS $STD_PATH && exit 0 ;;
    esac
done

(( !$# )) && [[ -f "$STD_PATH" ]] && feh $STD_PATH && exit 0 || [[ -f "$1" ]] && cp "$1" $STD_PATH && feh $STD_OPTIONS $STD_PATH && (( $VIEW_WALLPAPER )) && feh $STD_PATH
